* can't find platform plugins
#+begin_src comment
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
#+end_src

qt_standard_project_setup
qt_add_executable

add_library(Qt5::QWindowsIntegrationPlugin MODULE IMPORTED)


# QWindowsIntegrationPlugin is part of the Gui component
find_package(Qt5 COMPONENTS Gui REQUIRED)

install(
    FILES "$<TARGET_FILE:Qt5::QWindowsIntegrationPlugin>"
    DESTINATION bin/platforms
)

https://github.com/microsoft/vcpkg/issues/36250


On Windows qt5-qtbase only deploys the windows.dll platform plugin to the build folder.
This is done by vcpkg-ports/qt5-base/qtdeploy.ps1.
This is a problem as Qt supplies other platform plugins that consuming software may use.
I need the offscreen.dll platform plugin as my project uses it to run GUI unit tests.
vcpkg-ports/qt5-base/qtdeploy.ps1 only selectively deploys from the platforms plugins folder.
All other Qt plugin types are deployed fully.

Environment

OS: Windows
Compiler: Visual Studio 2022

Means you need to actually deploy the platform plugins (e.g. by running the qt6 depolyment scripts/api) or you need to have a qt.conf alongside the application telling it where to find the platform plugins.

When was the last time? Was it still qt5?
If yes that has extra deploy logic in vcpkg.
Qt6 however has itself an extra deployapi in cmake which you should use.

add_custom_command(TARGET demo_qt_cmake POST_BUILD COMMAND  Qt6::windeployqt ARGS $<TARGET_FILE:demo_qt_cmake>)
